# Generated by Django 6.0.2 on 2026-02-08 18:06

import core.models.company
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_display_id', models.CharField(default=core.models.company.generate_company_display_id, editable=False, max_length=8, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_domain', models.CharField(help_text='Example: company.com (without @)', max_length=255, unique=True)),
                ('db_alias', models.CharField(editable=False, help_text='Database alias used by Django router', max_length=50, unique=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('user_id', models.BigIntegerField()),
                ('company_display_id', models.CharField(max_length=50)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_display_id', models.CharField(db_index=True, help_text='Company display ID this user belongs to', max_length=8)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('password', models.CharField(default='pbkdf2_sha256$1200000$C093IIZDil09V9WA3jPkXu$cLrCtbt68Ojh5LbN69an6EM/WhUpkiMfEXq2RsRZJbU=', max_length=128)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_users',
                'indexes': [models.Index(fields=['company_display_id', 'email'], name='company_use_company_a62ad0_idx'), models.Index(fields=['company_display_id', 'username'], name='company_use_company_c4d796_idx')],
            },
        ),
        migrations.CreateModel(
            name='CricketEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_event_id', models.PositiveIntegerField(unique=True)),
                ('event_name', models.CharField(max_length=64)),
                ('short_name', models.CharField(blank=True, max_length=24)),
                ('start_date', models.DateField(default='2026-01-01')),
                ('end_date', models.DateField(default='2026-01-01')),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('organizer', models.CharField(blank=True, max_length=64, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('UPCOMING', 'Upcoming')], default='UPCOMING', max_length=16)),
                ('allow_predictions', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cricket_event',
                'managed': True,
                'indexes': [models.Index(fields=['event_name'], name='cricket_eve_event_n_08f489_idx'), models.Index(fields=['start_date'], name='cricket_eve_start_d_f5d16b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CricketMatchDetails',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_match_id', models.PositiveSmallIntegerField()),
                ('match_date', models.DateField(default='2026-01-01')),
                ('match_time', models.TimeField(default='19:30:00')),
                ('match_type', models.CharField(blank=True, max_length=16, null=True)),
                ('status_id', models.PositiveSmallIntegerField(choices=[(1, 'Scheduled'), (2, 'Live'), (3, 'Completed'), (4, 'Cancelled')], default=1)),
                ('location', models.CharField(blank=True, max_length=24, null=True)),
                ('stadium', models.CharField(blank=True, max_length=40, null=True)),
                ('match_name1', models.CharField(blank=True, max_length=80, null=True)),
                ('match_name2', models.CharField(blank=True, max_length=24, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('allow_predictions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.cricketevent')),
            ],
            options={
                'db_table': 'cricket_match_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CricketTeam',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_team_id', models.PositiveIntegerField(default=1)),
                ('team_name', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=8)),
                ('location', models.CharField(blank=True, max_length=32, null=True)),
                ('home_stadium', models.CharField(blank=True, max_length=40, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.cricketevent')),
            ],
            options={
                'db_table': 'cricket_team',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CricketPlayer',
            fields=[
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_player_id', models.PositiveIntegerField(help_text='Sequential player ID per event or team')),
                ('player_name', models.CharField(default='ABC', max_length=64)),
                ('short_name', models.CharField(blank=True, max_length=32, null=True)),
                ('role', models.CharField(choices=[('BATTER', 'Batter'), ('ALL_ROUNDER', 'All Rounder'), ('BOWLER', 'Bowler')], default='BATTER', max_length=16)),
                ('batting_style', models.CharField(blank=True, max_length=32, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.cricketevent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.cricketteam')),
            ],
            options={
                'db_table': 'cricket_player',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CricketMatchWinnerDetails',
            fields=[
                ('winner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_winners', to='core.cricketevent')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_details', to='core.cricketmatchdetails')),
                ('most_runs_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_runs_awards', to='core.cricketplayer')),
                ('most_wickets_taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_wickets_awards', to='core.cricketplayer')),
                ('player_of_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_of_match_awards', to='core.cricketplayer')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='core.cricketteam')),
            ],
            options={
                'db_table': 'cricket_match_winner_details',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cricketmatchdetails',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='core.cricketteam'),
        ),
        migrations.AddField(
            model_name='cricketmatchdetails',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='core.cricketteam'),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('leaderboard_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leaderboard_name', models.CharField(max_length=40)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('company_display_id', models.CharField(db_index=True, default='AAAAAAAA', help_text='Company display ID this user belongs to', max_length=8)),
                ('leaderboard_points_winner_team', models.IntegerField(default=4)),
                ('leaderboard_points_mom', models.IntegerField(default=3)),
                ('leaderboard_points_runs', models.IntegerField(default=3)),
                ('leaderboard_points_wickets', models.IntegerField(default=3)),
                ('created_by_user_id', models.UUIDField(blank=True, help_text='CompanyUser UUID who created this leaderboard', null=True)),
                ('created_on_1', models.DateField(default='2026-01-01')),
                ('tag1', models.CharField(blank=True, max_length=16, null=True)),
                ('tag2', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'leaderboards',
                'indexes': [models.Index(fields=['leaderboard_name'], name='leaderboard_leaderb_ab2bea_idx'), models.Index(fields=['event_id'], name='leaderboard_event_i_5fa427_idx'), models.Index(fields=['company_display_id'], name='leaderboard_company_9be455_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardPoints',
            fields=[
                ('leaderboard_points_id', models.AutoField(primary_key=True, serialize=False)),
                ('leaderboard_user_id', models.UUIDField(help_text='LeaderboardUser UUID')),
                ('match_id', models.UUIDField(blank=True, null=True)),
                ('points1', models.IntegerField(default=0)),
                ('points2', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leaderboard_points',
                'managed': True,
                'indexes': [models.Index(fields=['leaderboard_user_id'], name='leaderboard_leaderb_93e0b3_idx'), models.Index(fields=['match_id'], name='leaderboard_match_i_d8fa0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardUser',
            fields=[
                ('leaderboard_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leaderboard_id', models.UUIDField(help_text='Leaderboard UUID')),
                ('user_id', models.UUIDField(help_text='CompanyUser UUID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'leaderboard_users',
                'indexes': [models.Index(fields=['leaderboard_id'], name='leaderboard_leaderb_fcff32_idx'), models.Index(fields=['user_id'], name='leaderboard_user_id_bc3900_idx')],
                'unique_together': {('leaderboard_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('user_submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('match_id', models.UUIDField(blank=True, null=True)),
                ('predicted_winner_team_id', models.UUIDField(blank=True, null=True)),
                ('predicted_player_of_match_id', models.UUIDField(blank=True, null=True)),
                ('predicted_most_runs_player_id', models.UUIDField(blank=True, null=True)),
                ('predicted_most_wickets_taker_id', models.UUIDField(blank=True, null=True)),
                ('points_winner', models.IntegerField(default=0)),
                ('points_mom', models.IntegerField(default=0)),
                ('points_runs', models.IntegerField(default=0)),
                ('points_wickets', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.companyuser')),
            ],
            options={
                'db_table': 'user_submissions',
            },
        ),
        migrations.AddIndex(
            model_name='cricketteam',
            index=models.Index(fields=['short_name'], name='cricket_tea_short_n_3cbc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='cricketteam',
            index=models.Index(fields=['team_name'], name='cricket_tea_team_na_98b90a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cricketteam',
            unique_together={('event', 'display_team_id')},
        ),
        migrations.AddIndex(
            model_name='cricketplayer',
            index=models.Index(fields=['player_name'], name='cricket_pla_player__49243e_idx'),
        ),
        migrations.AddIndex(
            model_name='cricketplayer',
            index=models.Index(fields=['team'], name='cricket_pla_team_id_f0a989_idx'),
        ),
        migrations.AddIndex(
            model_name='cricketplayer',
            index=models.Index(fields=['event'], name='cricket_pla_event_i_6becb4_idx'),
        ),
        migrations.AddIndex(
            model_name='cricketplayer',
            index=models.Index(fields=['role'], name='cricket_pla_role_91c8d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cricketplayer',
            unique_together={('event', 'display_player_id', 'team')},
        ),
        migrations.AddIndex(
            model_name='cricketmatchwinnerdetails',
            index=models.Index(fields=['event'], name='cricket_mat_event_i_26b191_idx'),
        ),
        migrations.AddIndex(
            model_name='cricketmatchwinnerdetails',
            index=models.Index(fields=['match'], name='cricket_mat_match_i_2b2fda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cricketmatchwinnerdetails',
            unique_together={('event', 'match')},
        ),
        migrations.AddIndex(
            model_name='cricketmatchdetails',
            index=models.Index(fields=['match_date'], name='cricket_mat_match_d_e6f666_idx'),
        ),
        migrations.AddIndex(
            model_name='cricketmatchdetails',
            index=models.Index(fields=['event'], name='cricket_mat_event_i_338d94_idx'),
        ),
        migrations.AddIndex(
            model_name='cricketmatchdetails',
            index=models.Index(fields=['team1'], name='cricket_mat_team1_i_e9f08c_idx'),
        ),
        migrations.AddIndex(
            model_name='cricketmatchdetails',
            index=models.Index(fields=['team2'], name='cricket_mat_team2_i_fc574d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cricketmatchdetails',
            unique_together={('event', 'display_match_id')},
        ),
        migrations.AlterUniqueTogether(
            name='usersubmission',
            unique_together={('user', 'match_id')},
        ),
    ]
